name: Deploy Prod Environment

run-name: Deploy Notification Service Test - ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        shell: bash
        run: |
          docker build -t manueldevx/engine-bus-booking .
          docker push manueldevx/engine-bus-booking

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: ssh_into_server_and_deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            docker stop engine-bus-booking || true
            docker rm engine-bus-booking || true
            docker pull manueldevx/engine-bus-booking:latest
            docker run -d --name employer-client -dp 8080:8080 manueldevx/engine-bus-booking
